  name: Generate Cypress report
 on:
   push:
     branches:
       - 'master'
 jobs:
    cypress-run: 
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
 steps:
    - uses: actions/checkout@v2
    - name: Install a project with a clean slate
      run: |
        npm ci        
        $(npm bin)/cypress verify
    - name: Run Cypress tests
      run: npm run test:chrome
      continue-on-error: false
    - name: Copy test execution videos and screenshots
      run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screeshots
        
    - name: Merge test results into one
      run: npm run report:merge
      
    - name: Generate HTML report
      run: npm run report:generate
      
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
